version: '3'

includes:
  service: 
    taskfile: ./services/Taskfile.yaml
    # aliases: [s]
    dir: ./services

vars:
  MAIN_TFVARS_PATH: "./terraform.tfvars"

tasks:
  auth:
    cmds:
      - sed -i "/^access_token =/c\access_token = \"$(yc iam create-token)\"" {{.MAIN_TFVARS_PATH}}

  init:
    cmds:
      - ./scripts/init.sh
  
  plan:
    cmds:
      - terraform plan -var-file={{.MAIN_TFVARS_PATH}}

  validate:
    cmds:
      - terraform validate

  apply:
    cmds:
      - terraform apply -var-file={{.MAIN_TFVARS_PATH}}

  destroy:
    cmds:
      - terraform destroy -var-file={{.MAIN_TFVARS_PATH}}
